<?php

$defs ='
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="810mm"
   height="297mm"
   viewBox="0 0 810 297"
   version="1.1"
   id="svg8"
   inkscape:version="0.92.2 (5c3e80d, 2017-08-06)"
   sodipodi:docname="module.svg">
  <title
     id="title1465">Module</title>
  <defs
     id="defs2">
    <linearGradient
       inkscape:collect="always"
       id="linearGradient1253">
      <stop
         style="stop-color:#3469f6;stop-opacity:1;"
         offset="0"
         id="stop1249" />
      <stop
         style="stop-color:#3469f6;stop-opacity:0;"
         offset="1"
         id="stop1251" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       id="linearGradient1122">
      <stop
         style="stop-color:#349208;stop-opacity:1;"
         offset="0"
         id="stop1118" />
      <stop
         style="stop-color:#349208;stop-opacity:0;"
         offset="1"
         id="stop1120" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       id="linearGradient1018">
      <stop
         style="stop-color:#fb9208;stop-opacity:1;"
         offset="0"
         id="stop1014" />
      <stop
         style="stop-color:#fb9208;stop-opacity:0;"
         offset="1"
         id="stop1016" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       id="linearGradient852">
      <stop
         style="stop-color:#fe4939;stop-opacity:1;"
         offset="0"
         id="stop848" />
      <stop
         style="stop-color:#fe4939;stop-opacity:0;"
         offset="1"
         id="stop850" />
    </linearGradient>
    <linearGradient
       gradientTransform="matrix(0,-1,-1,0,164.7798,116.58298)"
       inkscape:collect="always"
       xlink:href="#linearGradient852"
       id="linearGradient854-0-4-4"
       x1="48.268921"
       y1="65.374023"
       x2="61.433113"
       y2="65.374023"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient852"
       id="linearGradient1391-2"
       gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(0,-1,-1,0,98.756859,128.5398)"
       x1="48.268921"
       y1="65.374023"
       x2="61.433113"
       y2="65.374023" />
    <linearGradient
       gradientTransform="translate(-19.661508,11.279672)"
       inkscape:collect="always"
       xlink:href="#linearGradient852"
       id="linearGradient854-4-2"
       x1="48.268921"
       y1="65.374023"
       x2="61.433113"
       y2="65.374023"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1018"
       id="linearGradient1451-0"
       gradientUnits="userSpaceOnUse"
       gradientTransform="rotate(-90,37.796677,91.065698)"
       x1="28.627672"
       y1="86.712479"
       x2="41.791756"
       y2="86.712479" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1018"
       id="linearGradient1020-8-1"
       x1="28.627672"
       y1="86.712479"
       x2="41.791756"
       y2="86.712479"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-0.02016824,9.6652473)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1018"
       id="linearGradient1162-9"
       x1="76.254562"
       y1="162.90543"
       x2="86.254562"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931542,-86.226357)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient852"
       id="linearGradient1164-1"
       x1="86.037529"
       y1="162.90543"
       x2="96.037529"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931542,-86.226357)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1122"
       id="linearGradient1160-9"
       x1="66.527534"
       y1="162.90543"
       x2="76.527534"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931542,-86.226357)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1253"
       id="linearGradient1158-7"
       x1="56.769032"
       y1="162.90543"
       x2="66.769035"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931542,-86.226357)" />
    <linearGradient
       gradientTransform="rotate(90,36.888951,95.667609)"
       inkscape:collect="always"
       xlink:href="#linearGradient1122"
       id="linearGradient1124-4-3-0-0-8"
       x1="46.566845"
       y1="98.962448"
       x2="59.73093"
       y2="98.962448"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       gradientTransform="translate(-17.69474,9.7354333)"
       inkscape:collect="always"
       xlink:href="#linearGradient1122"
       id="linearGradient1124-48-7"
       x1="46.566845"
       y1="98.962448"
       x2="59.73093"
       y2="98.962448"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1253"
       id="linearGradient1569-0"
       gradientUnits="userSpaceOnUse"
       gradientTransform="rotate(90,36.325677,114.84013)"
       x1="46.512707"
       y1="117.7935"
       x2="59.676792"
       y2="117.7935" />
    <linearGradient
       gradientTransform="translate(-17.905183,10.909996)"
       inkscape:collect="always"
       xlink:href="#linearGradient1253"
       id="linearGradient1255-2-0"
       x1="46.512707"
       y1="117.7935"
       x2="59.676792"
       y2="117.7935"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1018"
       id="linearGradient1162-9-7"
       x1="76.254562"
       y1="162.90543"
       x2="86.254562"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931589,-66.676709)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient852"
       id="linearGradient1164-1-1"
       x1="86.037529"
       y1="162.90543"
       x2="96.037529"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931589,-66.676709)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1122"
       id="linearGradient1160-9-7"
       x1="66.527534"
       y1="162.90543"
       x2="76.527534"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931589,-66.676709)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1253"
       id="linearGradient1158-7-1"
       x1="56.769032"
       y1="162.90543"
       x2="66.769035"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931589,-66.676709)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1253"
       id="linearGradient1158-7-1-0"
       x1="56.769032"
       y1="162.90543"
       x2="66.769035"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.93163,-54.047212)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1122"
       id="linearGradient1160-9-7-7"
       x1="66.527534"
       y1="162.90543"
       x2="76.527534"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.93163,-54.047212)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient852"
       id="linearGradient1164-1-1-8"
       x1="86.037529"
       y1="162.90543"
       x2="96.037529"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.93163,-54.047212)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1018"
       id="linearGradient1162-9-7-2"
       x1="76.254562"
       y1="162.90543"
       x2="86.254562"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.93163,-54.047212)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1253"
       id="linearGradient1158-7-1-0-2"
       x1="56.769032"
       y1="162.90543"
       x2="66.769035"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931631,-34.13878)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1122"
       id="linearGradient1160-9-7-7-2"
       x1="66.527534"
       y1="162.90543"
       x2="76.527534"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931631,-34.13878)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient852"
       id="linearGradient1164-1-1-8-2"
       x1="86.037529"
       y1="162.90543"
       x2="96.037529"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931631,-34.13878)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1018"
       id="linearGradient1162-9-7-2-9"
       x1="76.254562"
       y1="162.90543"
       x2="86.254562"
       y2="162.90543"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-12.931631,-34.13878)" />
    <linearGradient
       gradientTransform="translate(24.788571,3.2857569)"
       inkscape:collect="always"
       xlink:href="#linearGradient852"
       id="linearGradient854-5-9-2"
       x1="48.268921"
       y1="65.374023"
       x2="61.433113"
       y2="65.374023"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient1018"
       id="linearGradient1020-4-8-4"
       x1="28.627672"
       y1="86.712479"
       x2="41.791756"
       y2="86.712479"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(44.57089,1.5361508)" />
    <linearGradient
       gradientTransform="translate(26.61929,17.391823)"
       inkscape:collect="always"
       xlink:href="#linearGradient1122"
       id="linearGradient1124-7-3-6"
       x1="46.566845"
       y1="98.962448"
       x2="59.73093"
       y2="98.962448"
       gradientUnits="userSpaceOnUse" />
    <linearGradient
       gradientTransform="translate(26.65039,18.922983)"
       inkscape:collect="always"
       xlink:href="#linearGradient1253"
       id="linearGradient1255-4-0-7"
       x1="46.512707"
       y1="117.7935"
       x2="59.676792"
       y2="117.7935"
       gradientUnits="userSpaceOnUse" />
  </defs>
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="1"
     inkscape:cx="213.56729"
     inkscape:cy="775.32605"
     inkscape:document-units="mm"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1400"
     inkscape:window-height="1017"
     inkscape:window-x="-8"
     inkscape:window-y="-8"
     inkscape:window-maximized="1"
     inkscape:measure-start="684.355,873.825"
     inkscape:measure-end="561,842.746" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title>Module</dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>';
  
  ?>