ACCFAM, ACCMOD, AUTREHEBER, AUTRLIEUACC, AUTRLIEUAR, COMPOMENAG, CONDADD, CONDEDEV,
CONDEDUC, CONFL, DEFINTEL, DIPLOME, EMPLA1, EMPLA2, ETABSCOSPE, INSTITPLAC,
LIEUACC, LIEUPLAC, MODACC, MORALITE, MOTFININT, NEGLIG, PLACMOD, SANTE,
SECURITE, SOUTSOC, TYPDECJUD, VIOLFAM, VIOLPHYS, VIOLPSY, VIOLSEX

ACCFAM, ACCMOD, AUTREHEBER, AUTRLIEUACC, AUTRLIEUAR, COMPOMENAG, CONDADD, CONDEDEV,
CONDEDUC, CONFL, 

DATDECMIN, DATIP, DATJE, DATSIGN, 

DEFINTEL, ENQPENAL,
ETABSCOSPE, INSTITPLAC, LIEUACC, LIEUPLAC, MODACC, MORALITE, MOTIFSIG, NEGLIG,
NOTIFEVAL, ORIGIP, PLACMOD, SAISJUR, SANTE, SECURITE, SOUTSOC, TRANSIP,
TYPCLASSPE, TYPDECJUD, TYPETABSPE, TYPINTERDOM, VIOLFAM, VIOLPHYS, VIOLPSY, VIOLSEX,


ACCFAM, ACCMOD, AUTREHEBER, AUTRLIEUACC, AUTRLIEUAR, COMPOMENAG, CONDADD, CONDEDEV,
CONDEDUC, CONFL, DEFINTEL, 

DIPLOME,  ->KO 
EMPLA1,  ->KO 
EMPLA2,  -> KO


ETABSCOSPE, INSTITPLAC,
LIEUACC, LIEUPLAC, MODACC, MORALITE, 

MOTFININT, ->KO  
NEGLIG, 

PLACMOD,

SANTE,
SECURITE, SOUTSOC, TYPDECJUD, VIOLFAM, VIOLPHYS, VIOLPSY, VIOLSEX,


2019-01-09 15:53:56
SELECT NBFRAT,count(*)
FROM `DONNEES_TMP`
WHERE  `DONNEES_TMP`.`DateTraitement` = '2019-01-10 12:23:28'
GROUP BY `DONNEES_TMP`.`NBFRAT`
LIMIT 0 , 30

DATIP = 0000-00-00
